version: "3.8"
services:
  db:
    container_name: graduation
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: danglinh
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: linhDB
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
